// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrqozcykqcbzmpoibqru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJycW96Y3lrcWNiem1wb2licXJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NzU2NzUsImV4cCI6MjA3NDQ1MTY3NX0.UxREY0fFI9pztOSmEtUABo9vNWUi_ExBQtsRMtJZYJ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});